import { Roboto_Flex } from "next/font/google";
import type { Metadata } from "next";
import { ReactNode } from "react";

import "@/layouts/globals.css";
import { ThemeProvider } from "@/components/providers/theme-provider";
import NavBar from "@/components/layout/navBar";

const robotoFlex = Roboto_Flex({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={robotoFlex.className}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <NavBar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
