import { Roboto_Flex } from 'next/font/google'
import type { Metadata } from 'next'
import { ReactNode } from 'react'

import '@/layouts/globals.css'

const robotoFlex = Roboto_Flex({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

interface RootLayoutProps {
  children: ReactNode
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={robotoFlex.className}>{children}</body>
    </html>
  )
}
